using UnityUxmlGenerator.Captures;

namespace UnityUxmlGenerator;

internal sealed partial class UxmlGenerator
{
    private static string GenerateUxmlFactory(UxmlFactoryCapture capture)
    {
        return $$"""
// <auto-generated/>
#pragma warning disable

#nullable enable

namespace {{capture.ClassNamespace}}
{
    partial class {{capture.ClassName}}
    {
        {{GeneratedCodeAttribute}}
        public new class UxmlFactory : global::UnityEngine.UIElements.UxmlFactory<{{capture.ClassName}}, UxmlTraits> 
        {
        }
    }
}
""";
    }
}