using Microsoft.CodeAnalysis.CSharp.Syntax;
using UnityUxmlGenerator.Captures;
using UnityUxmlGenerator.Extensions;

namespace UnityUxmlGenerator;

internal sealed partial class UxmlGenerator
{
    private static string GenerateUxmlFactory(UxmlFactoryCapture uxmlFactory)
    {
        return $$"""
// <auto-generated/>

#nullable enable

namespace {{uxmlFactory.Class.GetParent<NamespaceDeclarationSyntax>()!.Name}}
{
    partial class {{uxmlFactory.ClassIdentifier}}
    {
        {{GeneratedCodeAttribute}}
        public new class UxmlFactory : global::UnityEngine.UIElements.UxmlFactory<{{uxmlFactory.ClassIdentifier}}, UxmlTraits> { }
    }
}
""";
    }
}