using System.Reflection;

namespace UnityUxmlGenerator;

internal sealed partial class UxmlGenerator
{
    private static readonly AssemblyName AssemblyName = typeof(UxmlGenerator).Assembly.GetName();

    private static readonly string GeneratedCodeAttribute =
        $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{AssemblyName.Name}", "{AssemblyName.Version}")]""";

    private static readonly string UxmlElementAttribute = $$"""
// <auto-generated/>
#pragma warning disable

#nullable enable

namespace {{AssemblyName.Name}}
{
    {{GeneratedCodeAttribute}}
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class UxmlElementAttribute : global::System.Attribute
    {
    }
}
""";

    private static readonly string UxmlAttributeAttribute = $$"""
// <auto-generated/>
#pragma warning disable

#nullable enable

namespace {{AssemblyName.Name}}
{
    {{GeneratedCodeAttribute}}
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class UxmlAttributeAttribute : global::System.Attribute
    {
        public UxmlAttributeAttribute(object? defaultValue = default)
        {
            DefaultValue = defaultValue;
        }

        public object? DefaultValue { get; }
    }
}
""";
}