namespace UnityUxmlGenerator;

internal sealed partial class UxmlGenerator
{
    private static readonly string GeneratedCodeAttribute =
        $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{typeof(UxmlGenerator).Assembly.GetName().Name}", "{typeof(UxmlGenerator).Assembly.GetName().Version}")]""";

    private static readonly string UxmlElementAttribute = $$"""
// <auto-generated/>

#nullable enable

namespace {{typeof(UxmlGenerator).Assembly.GetName().Name}}
{
    {{GeneratedCodeAttribute}}
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class UxmlElementAttribute : global::System.Attribute
    {
    }
}
""";

    private static readonly string UxmlAttributeAttribute = $$"""
// <auto-generated/>

#nullable enable

namespace {{typeof(UxmlGenerator).Assembly.GetName().Name}}
{
    {{GeneratedCodeAttribute}}
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class UxmlAttributeAttribute : global::System.Attribute
    {
        public UxmlAttributeAttribute(string defaultValue = "")
        {
            DefaultValue = defaultValue ?? string.Empty;
        }

        public string DefaultValue { get; }
    }
}
""";
}